management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  #
  # spring.rabbitmq.addresses=172.17.8.220
  #
  rabbitmq:
    host: 172.17.8.220
    password: admin
    username: admin
    virtual-host: default
  #
  # Mail Service
  #
  mail:
    host: "smtpout.secureserver.net"
    port: 465
    username: "ianache@crossnetcorp.com"
    password: CHANGEME
    protocol: smtp
    properties.mail.smtp:
      auth: true
      ssl.enable: true
      ssl.trust: "*"
    #  mail.smtp.connectiontimeout: 5000
    #  mail.smtp.timeout: 3000
    #  mail.smtp.writetimeout: 5000

notification:
  exchange: default
  businessevent:
    queue: queue.businessevent
    routingkey: queue.businessevent

  #
  # SME Settings
  sms:
    queue: queue.sms
    routingkey: queue.sms
  #
  # Mail Settings
  mail:
    from: ianache@crossnetcorp.com
    queue: queue.mail
    routingkey: queue.mail
  #
  # Webhook Settings
  webhook:
    queue: queue.webhook
    routingkey: queue.webhook
  #
  # WhatsApp Settings
  whatsapp:
    queue: queue.whatsapp
    routingkey: queue.whatsapp
  #
  # Push Settings
  push:
    queue: queue.push
    routingkey: queue.push